import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  cardRoot: {
    height: "400px",
    width: "350px",
    backgroundColor: "#CCCCCC",
    borderRadius: "10px",
    position: "relative",
    overflow: "hidden",
    margin: "20px",
    // zIndex: "1",
  },
  acceptContainer: {
    position: "absolute",
    height: "100%",
    width: "100%",
    backgroundColor: "#4B4B4B",
    position: "relative",
    right: "-110%",
    transition: "0.5s",
    display: "flex",
    flexDirection: "column",
    padding: "10px",
    alignItems: "center",
    overflowY: "scrollable",

    // zIndex: "1",
  },
  giftDetailsContainer: {
    width: "100%",
    height: "90%",
    alignSelf: "flex-start",
    display: "flex",
    flexDirection: "column",
    overflow: "auto",
  },
  textDetailsContainer: {
    padding: "10px",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  imageTwoContainer: {
    width: "50%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  imageTwo: {
    height: "80%",
    width: "80%",
    objectFit: "contain",
  },
  descriptionTextField: {
    height: "300px",
  },
  dialogContentContainer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    overflow: "auto",
  },
  confirmHeading: {
    marginBottom: "10px",
    fontSize: "20px",
    textAlign: "center",
    padding: "0 2px",
    alignItems: "center",
    justifyContent: "center",
  },
  viewContainer: {
    height: "100%",
    width: "100%",
    position: "absolute",
    display: "flex",
    justifyContent: "space-around",
    overflow: "auto",
    flexWrap: "wrap",
  },
  cardMain: {
    height: "100%",
    width: "100%",
    position: "absolute",
  },
  descriptionContainer: {
    height: "100%",
    width: "100%",
    position: "absolute",
    left: "-100%",
    backgroundColor: "#E9E9E9",
    transition: "0.4s",
    display: "flex",
    flexDirection: "column",
  },
  description: {
    height: "90%",
  },
  descriptionText: {
    padding: "10px 15px",
    color: "black",
    fontSize: "13px",
  },

  dialogPaper: {
    minHeight: "80vh",
    maxHeight: "80vh",
    minWidth: "80vw",
    maxWidth: "80vw",
    // padding: "10px",
  },
  dialogActionsRoot: {
    width: "100%",
    height: "80%",
    flexDirection: "flex-start",
    background: "black",
  },
  imageContainer: {
    width: "100%",
    height: "70%",
    backgroundColor: "white",
    borderTopLeftRadius: "10px",
    borderTopRightRadius: "10px",
  },
  titleContainer: {
    width: "100%",
    height: "30%",
    display: "flex",
    position: "relative",
    flexDirection: "column",
    alignItems: "center",
    alignContent: "center",
  },
  cardImage: {
    height: "100%",
    width: "100%",
    objectFit: "contain",
    // background: "contain",
  },
  giftTitle: {
    marginTop: "10px",
    color: "black",
    fontWeight: "500",
    fontSize: "14px",
    textAlign: "center",
  },
  learnButton: {
    position: "absolute",
    fontWeight: "400",
    color: "black",
    bottom: "10px",
    left: "10px",
  },
  selectButton: {
    position: "absolute",
    fontWeight: "400",
    bottom: "10px",
    color: "black",
    right: "10px",
  },
}));
